version: '3.1'

services:
  bot:
    container_name: memebot-bot
    build:
      dockerfile: docker/Dockerfile
      context: ..
      args:
        CLIENT_TOKEN_FILE: client_token
        TWITTER_API_TOKENS_FILE: twitter_api_tokens.json
        DATABASE_URI: "mongodb://db:27017"
    restart: always
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      default:
  db:
    container_name: memebot-db
    image: mongo:4.4.4-bionic
    restart: always
    volumes:
      - ../data/db:/data/db
      - ../src/config/mongod.yaml:/etc/mongo/mongod.yaml:ro
    networks:
      default:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24