---
name: mypy

on:
  push:
    branches: ["master"]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "docker/*"
  pull_request:
    branches: ["master"]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "docker/*"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Python
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync --all-groups && source .venv/bin/activate
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
