---
name: mypy

on:
  push:
    branches: ["master"]
    paths:
      - "requirements.txt"
      - "tests/requirements.txt"
      - "**.py"
      - "pyproject.toml"
      - "docker/*"
  pull_request:
    branches: ["master"]
    paths:
      - "requirements.txt"
      - "tests/requirements.txt"
      - "**.py"
      - "pyproject.toml"
      - "docker/*"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install mypy
        run: pip install mypy
      - name: Install requirements
        run: pip install -r requirements.txt -r tests/requirements.txt
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
