---
name: "lint/format"

on:
  pull_request:
    branches: ["master"]
    paths:
      - "**.py"
      - "pyproject.toml"
  push:
    branches: ["master"]
    paths:
      - "**.py"
      - "pyproject.toml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Lint with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check --diff

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Format with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: format --diff
